apiVersion: apps/v1 # Where in the API it resides
kind: Deployment # The kind of workload we're creating
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tlibaiheb/bpi-app-api
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/ihebb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "0000"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  ports:
    - port: 8086  # Port exposé par le service Kubernetes
      targetPort: 8086  # Port sur lequel  Spring Boot s'exécute dans le conteneur
  selector:
    app: backend
