apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-claim1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/iheb/docker/postgres/docker-pg-vol/data"


    