apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    tier: database
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
        tier: database
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_DB
              value: "ihebb"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "0000"
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgresql-claim1
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-claim1
        - name: postgresql-initdb
          configMap:
            name: postgresql-initdb-config

        
---
# Définition du service PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP



